<?php
  $block = $this->getLayout()->getBlock('category.product.grid');
  $_gridJsObject='fileuploader_fileuploader_productsJsObject';//$this->getJsObjectName();
?>

<script type="text/javascript">
//<![CDATA[
    var fileProducts = $H(<?php echo $this->getProductsJson() ?>);
    $('in_file_products').value = fileProducts.toQueryString();

    function registerCategoryProduct(grid, element, checked){
       if(checked){
            if(element.positionElement){
                element.positionElement.disabled = false;
            }
            fileProducts.set(element.value, 0);
        }
        else{
            if(element.positionElement){
                element.positionElement.disabled = true;
            }
            fileProducts.unset(element.value);
        }
        $('in_file_products').value = fileProducts.toQueryString();
        grid.reloadParams = {'selected_products[]':fileProducts.keys()};
    }
    function categoryProductRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                fileuploader_product_id = checkbox[0].value;
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                <?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }
    function positionChange(event){
        var element = Event.element(event);
        if(element && element.checkboxElement && element.checkboxElement.checked){
            fileProducts.set(element.checkboxElement.value, element.value);
            $('in_file_products').value = fileProducts.toQueryString();
        }
    }

    var tabIndex = 1000;
    function categoryProductRowInit(grid, row){
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        var position = $(row).getElementsByClassName('input-text')[0];
        if(checkbox && position){
            checkbox.positionElement = position;
            position.checkboxElement = checkbox;
            position.disabled = !checkbox.checked;
            position.tabIndex = tabIndex++;
            Event.observe(position,'keyup',positionChange);
        }
    }
    <?php echo $_gridJsObject ?>.rowClickCallback = categoryProductRowClick;
    <?php echo $_gridJsObject ?>.initRowCallback = categoryProductRowInit;
    <?php echo $_gridJsObject ?>.checkboxCheckCallback = registerCategoryProduct;
    <?php echo $_gridJsObject ?>.rows.each(function(row){categoryProductRowInit( <?php echo $_gridJsObject ?>, row)});
//]]>
</script>
<h1><?php ?></h1>